services:
  - type: web
    name: it-ticketing-system
    env: python
    buildCommand: ""
    startCommand: python app.py
    plan: free
    envVars:
      - key: MAIL_USERNAME
        value: shahdhir08@gmail.com
      - key: MAIL_PASSWORD
        value: exua dznq vuxl imcs
